### ISSUE TITLE
CRTool "Start over with a new review" button should only clear CRTool-related local storage values

### ISSUE THREAD

**Issue by Scotchester** [cfpb/curriculum-review-tool#337]
[The code that clears local storage](https://github.com/cfpb/teachers-digital-platform/blob/master/teachers_digital_platform/crtool/src/js/business.logic/repository.js#L7-L9) when a user selects "Start over with a new review" clears _all_ local storage values for the current domain, potentially clearing out values unrelated to TDP that we want to leave in place.

```js
    clearAllData() {
        localStorage.clear();
    },
```

We should change this to only clear values that were set by the CRTool.

**Comment by nbucknor** [comment]
This is no longer relevant.
